### ISSUE TITLE
Getting ERROR RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.

### ISSUE THREAD

**Issue by diegodorgam** [hubot-scripts/hubot-devops-reactions#5]
Hi there, 
I'm trying to use it in my hubot, and I've installed the script, but when I call "devops reactions" I get  this error:

``` log
ERROR RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
  at String.normalize (native)
  at Object.src (/Users/diegoaguilera/www/bot/node_modules/jsdom/lib/jsdom/level2/html.js:220:21)
  at /Users/diegoaguilera/www/bot/node_modules/jsdom/lib/jsdom.js:274:18
  at Array.forEach (native)
  at processHTML (/Users/diegoaguilera/www/bot/node_modules/jsdom/lib/jsdom.js:269:20)
  at Request._callback (/Users/diegoaguilera/www/bot/node_modules/jsdom/lib/jsdom.js:205:7)
  at Request.self.callback (/Users/diegoaguilera/www/bot/node_modules/request/main.js:122:22)
  at emitTwo (events.js:100:13)
  at Request.emit (events.js:185:7)
  at Request.<anonymous> (/Users/diegoaguilera/www/bot/node_modules/request/main.js:661:16)
  at emitOne (events.js:95:20)
  at Request.emit (events.js:182:7)
  at IncomingMessage.<anonymous> (/Users/diegoaguilera/www/bot/node_modules/request/main.js:623:14)
  at emitNone (events.js:85:20)
  at IncomingMessage.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:906:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

Any ideas on how to fix it?

**Comment by wuservices** [comment]
I had things working many months (a year?) ago, and just tried to spin things up again and got the same error. Did you find a solution?
